config/routes.rb
Polycule::Application.routes.draw do

  get "invites/new" => "invite#new"
  post "invites" => "invite#create"

  get "users/sign_up" => "home#index"
  
  devise_for :users
  
  get "graph/index"

  resources :relationships
  resources :people

  get "home/index"
  get "/graph" => "graph#index"

  root :to => 'home#index'

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :email
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :birthday, :city, :country, :email, :facebook, :fetlife, :gender, :house, :name, :nickname, :note, :okcupid, :state, :twitter

  has_many :relationships
  has_many :partners, :through => :relationships, :source => :partner
  has_many :relationships_in, :class_name => "Relationship", :foreign_key => "partner_id"
  has_many :partners_in, :through => :relationships_in, :source => :person
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :fluidbonded, :kind, :kinky, :married, :note, :sexual, :since, :person_id, :partner_id, :until
  belongs_to :person
  belongs_to :partner, :class_name => 'Person'
  validates_each :person_id do |record, attr, value|
    if value == record.partner_id
      record.errors.add(attr, 'in relationship to self not allowed')
    end
    if record.person.partners_in.map(&:id).include?(record.partner_id)
      record.errors.add(attr, record.person.name + 
        ' can only be listed as in a relationship with the partner from the other direction')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!

end

app/controllers/graph_controller.rb
class GraphController < ApplicationController
  def index
    render
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!, :except => [:index]

  def index
  end
end

app/controllers/invite_controller.rb
class InviteController < ApplicationController

  before_filter :authenticate_user!, :except => [:new,:create]

  def new
    @invite = Invite.new
  end

  def create
    @invite = Invite.new(params[:invite])

    if @invite.save
      redirect_to root_path, notice: 'Invite was successfully created.'
    else
      render action: "new"
    end
  end
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # GET /relationships
  # GET /relationships.json
  def index
    @relationships = Relationship.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @relationships }
    end
  end

  # GET /relationships/1
  # GET /relationships/1.json
  def show
    @relationship = Relationship.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relationship }
    end
  end

  # GET /relationships/new
  # GET /relationships/new.json
  def new
    @relationship = Relationship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relationship }
    end
  end

  # GET /relationships/1/edit
  def edit
    @relationship = Relationship.find(params[:id])
  end

  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = Person.find(params[:relationship][:person_id]).relationships.build(params[:relationship])
    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: 'Relationship was successfully created.' }
        format.json { render json: @relationship, status: :created, location: @relationship }
      else
        format.html { render action: "new" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /relationships/1
  # PUT /relationships/1.json
  def update
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      if @relationship.update_attributes(params[:relationship])
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy

    respond_to do |format|
      format.html { redirect_to relationships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invite_helper.rb
module InviteHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/graph/index.html.erb
<h1>Graph#index</h1>
<p>Find me in app/views/graph/index.html.erb</p>

app/views/home/index.html.erb
<h1>My Polycule</h1>

<% if user_signed_in? %>
	<p><%= link_to 'People', people_path %></p>
	<p><%= link_to 'Relationships', relationships_path %></p>
	<p><%= link_to 'Visualization', graph_path %></p>
<% else %>
	<p><%= link_to 'Sign up', invites_new_path %></p>
<% end %>

app/views/invite/_form.html.erb
<%= form_for(@invite) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invite/new.html.erb
<h1>New Invite</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polycule</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
		<% if user_signed_in? %>
		Signed in as <%= current_user.email %>. Not you?
		<%= link_to "Log out", destroy_user_session_path, :method => :delete %>
		<% else %>
			<%= link_to "Log in", new_user_session_path %>
		<% end %>
	</div>	
	

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :house %><br />
    <%= f.text_field :house %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :okcupid %><br />
    <%= f.text_field :okcupid %>
  </div>
  <div class="field">
    <%= f.label :fetlife %><br />
    <%= f.text_field :fetlife %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Nickname</th>
    <th>Gender</th>
    <th>Birthday</th>
    <th>House</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Email</th>
    <th>Twitter</th>
    <th>Facebook</th>
    <th>Okcupid</th>
    <th>Fetlife</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.nickname %></td>
    <td><%= person.gender %></td>
    <td><%= person.birthday %></td>
    <td><%= person.house %></td>
    <td><%= person.city %></td>
    <td><%= person.state %></td>
    <td><%= person.country %></td>
    <td><%= person.email %></td>
    <td><%= person.twitter %></td>
    <td><%= person.facebook %></td>
    <td><%= person.okcupid %></td>
    <td><%= person.fetlife %></td>
    <td><%= person.note %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Nickname:</b>
  <%= @person.nickname %>
</p>

<p>
  <b>Gender:</b>
  <%= @person.gender %>
</p>

<p>
  <b>Birthday:</b>
  <%= @person.birthday %>
</p>

<p>
  <b>House:</b>
  <%= @person.house %>
</p>

<p>
  <b>City:</b>
  <%= @person.city %>
</p>

<p>
  <b>State:</b>
  <%= @person.state %>
</p>

<p>
  <b>Country:</b>
  <%= @person.country %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>

<p>
  <b>Twitter:</b>
  <%= @person.twitter %>
</p>

<p>
  <b>Facebook:</b>
  <%= @person.facebook %>
</p>

<p>
  <b>Okcupid:</b>
  <%= @person.okcupid %>
</p>

<p>
  <b>Fetlife:</b>
  <%= @person.fetlife %>
</p>

<p>
  <b>Note:</b>
  <%= @person.note %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Person %><br />	
	<%= collection_select( :relationship, :person_id, Person.all, :id, :name, {} ) -%>
  </div>
  <div class="field">
    <%= f.label :Partner %><br />
	<%= collection_select( :relationship, :partner_id, Person.all, :id, :name, {} ) -%>
  </div>
  <div class="field">
    <%= f.label :since %><br />
    <%= f.date_select :since %>
  </div>
  <div class="field">
    <%= f.label :until %><br />
    <%= f.date_select :until %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :married %><br />
    <%= f.check_box :married %>
  </div>
  <div class="field">
    <%= f.label :fluidbonded %><br />
    <%= f.check_box :fluidbonded %>
  </div>
  <div class="field">
    <%= f.label :sexual %><br />
    <%= f.check_box :sexual %>
  </div>
  <div class="field">
    <%= f.label :kinky %><br />
    <%= f.check_box :kinky %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h1>Editing relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<h1>Listing relationships</h1>

<table>
  <tr>
    <th>Person</th>
    <th>Partner</th>
    <th>Since</th>
    <th>Until</th>
    <th>Kind</th>
    <th>Married</th>
    <th>Fluidbonded</th>
    <th>Sexual</th>
    <th>Kinky</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relationships.each do |relationship| %>
  <tr>
    <td><%= relationship.person.name %></td>
    <td><%= relationship.partner.name %></td>
    <td><%= relationship.since %></td>
    <td><%= relationship.until %></td>
    <td><%= relationship.kind %></td>
    <td><%= relationship.married %></td>
    <td><%= relationship.fluidbonded %></td>
    <td><%= relationship.sexual %></td>
    <td><%= relationship.kinky %></td>
    <td><%= relationship.note %></td>
    <td><%= link_to 'Show', relationship %></td>
    <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
    <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h1>New relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Person:</b>
  <%= @relationship.person.name %>
</p>

<p>
  <b>Partner:</b>
  <%= @relationship.partner.name %>
</p>

<p>
  <b>Since:</b>
  <%= @relationship.since %>
</p>

<p>
  <b>Until:</b>
  <%= @relationship.until %>
</p>

<p>
  <b>Kind:</b>
  <%= @relationship.kind %>
</p>

<p>
  <b>Married:</b>
  <%= @relationship.married %>
</p>

<p>
  <b>Fluidbonded:</b>
  <%= @relationship.fluidbonded %>
</p>

<p>
  <b>Sexual:</b>
  <%= @relationship.sexual %>
</p>

<p>
  <b>Kinky:</b>
  <%= @relationship.kinky %>
</p>

<p>
  <b>Note:</b>
  <%= @relationship.note %>
</p>


<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>